version: "3.1"

services:
  db:
    container_name: voucher-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: devfloydbr
      POSTGRES_PASSWORD: devfloydbr
      POSTGRES_DB: voucherdb
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
